services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tiptrip
      - POSTGRES_DB=tiptrip_db
    volumes:
      - ./db_data/postgres_data:/var/lib/postgresql/data
    networks:
      - tiptrip_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: .
    container_name: tiptrip
    ports:
      - 5000:5000
    networks:
      - tiptrip_network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  tiptrip_network:
    driver: bridge
