version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5430:5432
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=tt_admin
      - POSTGRES_PASSWORD=tip_trip
      - POSTGRES_DB=tip_trip
    volumes:
      - ./db_data/postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tt_admin"]  # Verifica si PostgreSQL est치 listo
      interval: 10s  # Intervalo de verificaci칩n
      timeout: 5s    # Tiempo m치ximo para esperar respuesta
      retries: 5     # Reintentos antes de fallar
      start_period: 30s  # Tiempo de espera antes de la primera verificaci칩n

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    networks:
      - backend
    depends_on:
      - postgres

  app:
    build:
      context: .
    container_name: app
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy

networks:
  backend:
    driver: bridge

# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
